server:
  port: 10000

# redis单节点配置
spring:
  redis:
    database: 0
    host: 106.52.80.63
    port: 6379
    password: ""
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 2000
        min-idle: 1

logging:
  file-path: /logs
  level:
    com:
      wuhunyu:
        code_gen: debug
    org:
      springframework: warn