server:
  port: 10000

# redis单节点配置
spring:
  redis:
    database: 0
    host: 106.52.80.63
    port: 6379
    password: ""
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 2000
        min-idle: 1

# 内置task线程池配置
task-config:
  # 是否启用线程池配置
  enabled: true
  # 核心线程数
  core-num: 10
  # 最大线程数
  max-num: 15
  # 线程空闲秒数
  idle-second-num: 60
  # 阻塞队列等待线程数
  wait-num: 3
  # 线程池名称前缀
  task-name-prefix: "task-thread-"

logging:
  file-path: /logs
  level:
    com:
      wuhunyu:
        code_gen: debug
    org:
      springframework: warn